### ISSUE TITLE
FileNotFoundError on single step forecast command

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [sheoyon-jhin/ANCDE#5]
Running single step forecasting gives me this error

`python3 stock.py --seed 2021 --input_seq 24 --output_seq 1 --model="ancde_forecasting" --h_channel 12 --hh_channel 12 --layer 2 --lr 0.001 --soft '' --slope_check 'True' --timewise '' --attention_channel 4 --attention_attention_channel 8 --step_mode 'valloss'`

```
in X.shape torch.Size([3661, 24, 6])
6

parameter of Neural CDE 1751

parameter of ORIGINAL ODE FUNC 1248

parameter of ATTENTION ODE FUNC 292
valloss
Starting training for model:

ANCDE_forecasting(
  input_channels=6, hidden_channels=12, output_channels=1, initial=True
  (func_f): FinalTanh_ff6(
    input_channels: 6, hidden_channels: 4, hidden_hidden_channels: 8, num_hidden_layers: 2
    (linear_in): Linear(in_features=6, out_features=8, bias=True)
    (linear_test): Linear(in_features=8, out_features=4, bias=True)
    (linears): ModuleList(
      (0): Linear(in_features=4, out_features=4, bias=True)
    )
    (linear_out): Linear(in_features=4, out_features=36, bias=True)
  )
  (func_g): FinalTanh(
    input_channels: 6, hidden_channels: 12, hidden_hidden_channels: 12, num_hidden_layers: 2
    (linear_in): Linear(in_features=12, out_features=12, bias=True)
    (linears): ModuleList(
      (0): Linear(in_features=12, out_features=12, bias=True)
    )
    (linear_out): Linear(in_features=12, out_features=72, bias=True)
  )
  (STE): Hardsigmoid(
    (act): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (initial_network): Linear(in_features=6, out_features=6, bias=True)
  (feature_extractor): Linear(in_features=6, out_features=12, bias=True)
  (linear): Linear(in_features=12, out_features=6, bias=True)
  (time_attention): Linear(in_features=6, out_features=1, bias=True)
)


/usr/local/envs/neuralcde/lib/python3.7/site-packages/torch/cuda/memory.py:234: FutureWarning: torch.cuda.reset_max_memory_allocated now calls torch.cuda.reset_peak_memory_stats, which resets /all/ peak memory stats.
  FutureWarning)
  0%|          | 0/300 [00:00<?, ?it/s]Traceback (most recent call last):
  File "stock.py", line 170, in <module>
    main()
  File "stock.py", line 126, in main
    step_mode=step_mode,
  File "/content/ANCDE/experiments/common.py", line 800, in main_forecasting
    step_mode,
  File "/content/ANCDE/experiments/common.py", line 275, in _train_loop_forecasting
    times, train_coeffs, lengths, slope, stream=True, **kwargs
  File "/usr/local/envs/neuralcde/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/ANCDE/experiments/models/metamodel.py", line 647, in forward
    **kwargs)
  File "/content/ANCDE/experiments/models/../../controldiffeq/cdeint_module.py", line 239, in ancde_bottom
    out = odeint(func=vector_field, y0=z0, t=t, **kwargs)
  File "/usr/local/envs/neuralcde/lib/python3.7/site-packages/torchdiffeq/_impl/adjoint.py", line 129, in odeint_adjoint
    ys = OdeintAdjointMethod.apply(*y0, func, t, flat_params, rtol, atol, method, options)
  File "/usr/local/envs/neuralcde/lib/python3.7/site-packages/torchdiffeq/_impl/adjoint.py", line 18, in forward
    ans = odeint(func, y0, t, rtol=rtol, atol=atol, method=method, options=options)
  File "/usr/local/envs/neuralcde/lib/python3.7/site-packages/torchdiffeq/_impl/odeint.py", line 76, in odeint
    solution = solver.integrate(t)
  File "/usr/local/envs/neuralcde/lib/python3.7/site-packages/torchdiffeq/_impl/solvers.py", line 91, in integrate
    dy = self.step_func(self.func, t0, t1 - t0, y0)
  File "/usr/local/envs/neuralcde/lib/python3.7/site-packages/torchdiffeq/_impl/fixed_grid.py", line 29, in step_func
    return rk_common.rk4_alt_step_func(func, t, dt, y)
  File "/usr/local/envs/neuralcde/lib/python3.7/site-packages/torchdiffeq/_impl/rk_common.py", line 77, in rk4_alt_step_func
    k4 = func(t + dt, tuple(y_ + dt * (k1_ - k2_ + k3_) for y_, k1_, k2_, k3_ in zip(y, k1, k2, k3)))
  File "/usr/local/envs/neuralcde/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/envs/neuralcde/lib/python3.7/site-packages/torchdiffeq/_impl/adjoint.py", line 122, in forward
    return (self.base_func(t, y[0]),)
  File "/content/ANCDE/experiments/models/../../controldiffeq/cdeint_module.py", line 70, in __call__
    np.save(self.file, self.h_prime_list.cpu().detach().numpy())
  File "<__array_function__ internals>", line 6, in save
  File "/usr/local/envs/neuralcde/lib/python3.7/site-packages/numpy/lib/npyio.py", line 524, in save
    file_ctx = open(file, "wb")
FileNotFoundError: [Errno 2] No such file or directory: '/content/ANCDE/experiments/Google_h_prime/23326.npy'
  0%|          | 0/300 [00:00<?, ?it/s]

```

**Comment by liuyueChang** [comment]
I have encountered the same problem as you. How did you solve it ? 
Thank you!

**Comment by sheoyon-jhin** [comment]
Hello, Sorry for the late answer. 
'FileNotFoundError' might be alerted due to missing folders.
So, I just added a few lines to create a folder (such as Google_h_prime).
